name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Windows
            preset: Windows Desktop
            output: release/ChromAura_Windows.zip
            

          - platform: Linux
            preset: Linux
            output: release/ChromAura_Linux.zip

          - platform: MacOS
            preset: macOS
            output: release/ChromAura_MacOS.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.2
          use-dotnet: true
          include-templates: true
  
      - name: Check environment
        run: |
          godot --version
          dotnet --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgles2 \
            libgl1 \
            libegl1 \
            libusb-1.0-0

      - name: Import project
        run: |
          godot --headless --path chrom-aura --editor --quit

      - name: Create build directory
        run: |
          mkdir -p "chrom-aura/$(dirname '${{ matrix.output }}')"

      - name: Export
        run: |
          godot --headless --path chrom-aura --export-release "${{ matrix.preset }}" "${{ matrix.output }}"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ChromAura-${{ matrix.platform }}
          path: ${{ matrix.output }}

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: ChromAura-Windows
          path: release

      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: ChromAura-Linux
          path: release

      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: ChromAura-MacOS
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/ChromAura_Windows.zip
            release/ChromAura_Linux.zip
            release/ChromAura_MacOS.zip
          generate_release_notes: true
